image: node:10

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay

stages:
  - install
  - test
  - release
  #- pages
  - deploy
  - trigger

build:
  stage: install
  script:
    - npm install
    - npm install -g json-server
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  before_script:
    - whoami
    - Xvfb :99 -screen 0 1024x768x16 &> xvfb.log &
    - export DISPLAY=:99.0
    - npm start --prefix jsonapi-server-mock-lintol/ &
  image: martinnaughton/nightwatch-e2e-headless:java8
  script: 
    - ls /usr/bin/google-chrome 
    #- npm run test
  artifacts:
    paths:
      - test/unit/coverage/
  dependencies:
    - build

#pages:
#  stage: pages
#  dependencies:
#    - test 
#  script:
#    - mv test/unit/coverage/lcov-report/ public/
#  artifacts:
#    paths:
#      - public
#    expire_in: 30 days
#  only:
#    - master

release:
  stage: release
  script:
    - npm run build
    - echo "CI_BUILD_REF=$CI_BUILD_REF\nCI_COMMIT_SHA=$CI_COMMIT_SHA" > CI_BUILD_REF
  artifacts:
    paths:
      - dist
      - CI_BUILD_REF
  dependencies:
    - build
  only:
    - master

deploy:
  image: garland/aws-cli-docker
  stage: deploy
  dependencies:
    - release
  script:
    - tar -czf frontend-build.tgz dist
    - aws --endpoint-url https://mo.ev.openindustry.in s3api put-object --bucket $AWS_FRONTEND_BUCKET --key front-end-$CI_COMMIT_SHA.tgz --body frontend-build.tgz
    - aws --endpoint-url https://mo.ev.openindustry.in s3api put-object --bucket $AWS_FRONTEND_BUCKET --key front-end-latest.tgz --body frontend-build.tgz
  only:
    - master

trigger:
  image: odise/busybox-curl
  stage: trigger
  dependencies:
    - release
  script:
    - echo curl -X POST -F token=$GITLAB_BACKEND_TRIGGER -F ref=$GITLAB_BACKEND_TRIGGER_REF $GITLAB_BACKEND_TRIGGER_URL
    - curl -X POST -F token=$GITLAB_BACKEND_TRIGGER -F ref=$GITLAB_BACKEND_TRIGGER_REF $GITLAB_BACKEND_TRIGGER_URL
  only:
    - master
